name: Personal Blog Content
on:
  push:
    branches:
      - main

jobs:
  Deploy-Content-To-Personal-Blog:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy content to the personal blog
        run: |
          curl -X POST https://api.github.com/repos/ikhvostenkov/blog-platform/dispatches \
          -u ${{ secrets.GITHUB_TOKEN }} \
          --data '{"event_type": "content-deploy", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
